apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-rb
subjects:
- kind: ServiceAccount
  name: github-actions # name of your service account
  namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io