az storage container create -n client --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n eventattendeeuploadedfiles   --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n eventlogo eventsponsors   --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n eventlogo -n eventsponsors   --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n {eventlogo,loginpageagenda}    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n eventlogo    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n loginpageagenda    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n loginpagefootergraphics    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n loginpageheaderlogo    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n loginpagesplashimages    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n mailattachment    --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n profileimage  --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n quizcertificatecontainer  --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n registrationsetbanner  --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n repprofileimages  --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n roomtemplates  --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n sampledocuments --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n thankyoupageheadergraphics --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n thankyoupagesplashimages --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n webinarlogo --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n whitelistedemailaddresses --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n attendees --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT
az storage container create -n eventbrochure --public-access blob --account-name uatvemsblobstorage --account-key kEzDKc4meMXbmAKtSgkdpN4BvrD/PslSY7RbD6ABkK0RKxwKLDL1huqFXYdglj0pH9ZtofFvRvFU+AStGXQucA==  --resource-group Virtualplatform_UAT