apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: myvirtrio-cert
  # namespace: akv-test
spec:
  vault:
    name: uatvems-kv # 1. name of key vault
    object:
      name: myvirtrio-cert-new # 2. name of the akv object
      type: certificate # 3. akv object type
  output: 
    secret: 
      name: myvirtrio-newssl-cert # 4. kubernetes secret name
      type: kubernetes.io/tls
