apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: ssl-cert-fm 
  # namespace: akv-test
spec:
  vault:
    name: fm-vems-kv # 1. name of key vault
    object:
      name: ssl-fm-cert # 2. name of the akv object
      type: certificate # 3. akv object type
  output: 
    secret: 
      name: fmmyvirtrio-ssl-cert # 4. kubernetes secret name
      type: kubernetes.io/tls
